version: 0.1
   
phases:
  install:
    commands:
      - gem install minima 
      - gem install link-checker
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 nerdthought.net-staging ********"
      - aws s3 sync _site/ s3://nerdthought.net-staging
      - echo "******** Checking links ********"
      - check-links _site