version: 0.1
   
phases:
  install:
    commands:
      - gem install minima 
      - gem install link-checker
      - gem install jekyll:3.7.3 jekyll-paginate jekyll-sitemap jekyll-gist
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - JEKYLL_ENV=production jekyll build --verbose 
      - echo "******** Uploading to S3 nerdthought.net-staging ********"
      - aws s3 sync _site/ s3://nerdthoughts.net-staging --delete
