version: 0.1
   
phases:
  install:
    commands:
      - gem install minima 
  build:
    commands:
      - echo "******** Copying to S3 nerdthoughts.net-staging to www.nerdthoughts.net ********"
      - aws s3 sync s3://nerdthoughts.net-staging s3://www.nerdthoughts.net --delete
      - aws s3 sync s3://nerdthoughts.net-staging s3://nerdthoughts.net --delete      
