version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll:3.7.3 minima:2.0 jekyll-feed:0.6
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build --verbose --drafts
      - echo "******** Uploading to S3 nerdthoughts.net-staging ********"
      - aws s3 sync _site/ s3://nerdthoughts.net-staging
