version: 0.2
   
phases:
  install:
    commands:
      - gem update --system
      - gem install bundler
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - apt-get install nodejs
      - bundle install
  test:
    spellcheck:
    - cd test/spellcheck
    - sh run_spellcheck.sh
    - cd ../..
  build:
    commands:
      - echo "******** Building Staging Jekyll site with drafts ********"
      - bundle exec jekyll build --drafts --verbose
      - echo "******** Uploading to S3 nerdthought.net-staging ********"
      - aws s3 sync _site/ s3://nerdthoughts.net-staging --delete

      - echo "******** Building Production Jekyll site ********"
      - rm -r _site
      - JEKYLL_ENV=production bundle exec jekyll build --verbose
      - echo "******** Copying to S3 nerdthoughts.net-staging to www.nerdthoughts.net ********"
      - aws s3 sync _site/ s3://www.nerdthoughts.net --delete
      - aws s3 sync _site/ s3://nerdthoughts.net --delete      

      - echo "******** Logging Build Event ********"
      - pwd
      - mkdir log
      - cd log
      - mkdir general_events
      - ls -la
      - cd general_events
      - ls -la
      - pwd
      - cd ..
      - cd ..
      - pwd
      - cp build_event_json.txt log/general_events/
      - aws s3 sync log/ s3://aws-s3-to-es     





