version: 0.1
   
phases:
  install:
    commands:
      - gem install bundler
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - apt-get install nodejs
      - bundle install
  stage_build:
    commands:
      - echo "******** Building Staging Jekyll site with drafts ********"
      - bundle exec jekyll build --drafts --verbose
      - echo "******** Uploading to S3 nerdthought.net-staging ********"
      - aws s3 sync _site/ s3://nerdthoughts.net-staging --delete

  prod_build:
    commands:
      - echo "******** Building Production Jekyll site ********"
      - JEKYLL_ENV=production bundle exec jekyll build --verbose
      - echo "******** Copying to S3 nerdthoughts.net-staging to www.nerdthoughts.net ********"
      - aws s3 sync _site/ s3://www.nerdthoughts.net --delete
      - aws s3 sync _site/ s3://nerdthoughts.net --delete      




