version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll minima jekyll-feed
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - JEKYLL_ENV=production jekyll build --verbose 
      - echo "******** Uploading to S3 nerdthought.net-staging ********"
      - aws s3 sync _site/ s3://nerdthoughts.net-staging --delete
